export { Heading } from './Heading/Heading'
export { P } from './P/P'
export { Label } from './Label/Label'
export { Button } from './Button/Button'
export { Rating } from './Rating/Rating'
export { Card } from './Card/Card'
